version: '2'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    networks:
      - api
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5432

volumes:
    sample_db: {}